version: 2
jobs:
  deploy_dev: 
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: # 順に実行したいコマンドとコマンドに名前をつけます
          name: install
          command: yarn install
      - run:
          name: build
          command: yarn build
      - run:
          name: deploy to Firebase Hosting
          command: node_modules/.bin/firebase deploy --project "recipe-app-f1f3c" --token "$FIREBASETOKEN" # プロジェクト上のfirebase-toolsでデプロイします

workflows:
  version: 2
  deploy_dev: # ワークフローの名前
    jobs:
      - deploy_dev: # 上で定義したジョブを指定します
          filters:
            branches:
              only: develop # developブランチのみを実行対象とします
